### ISSUE TITLE
Issue with updating assignment and monadic verbs

### ISSUE THREAD

**Issue by refi64** [JohnEarnest/ok#31] opened 2015-11-08 03:44 UTC
```
f:{}
(f|:) / sets f to 'f|'; same with f+:, f-:, etc
```

I would think this would chain the verbs. Well, it kind of _does_, but it overwrites `f` in the process. I know `a+:b` is updated assignment, but this has no rhs.

Unless this is a K5 feature or something?

**Comment by JohnEarnest** [comment] 2020-04-04 01:27
Looking back at this ticket, I'm kinda baffled about the intended behavior here.

The expression `f|:` is desugared by oK's parser into `f:f|`, which is precisely what it does.

Closing. Feel free to reopen if you still care and you can clarify a use-case.

**Closed as completed by JohnEarnest** 2020-04-04 01:27 UTC
